version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-telecall
    restart: always
    environment:
      POSTGRES_USER: telecall
      POSTGRES_PASSWORD: telecall
      POSTGRES_DB: telecalldb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: